/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Vehicle carA = new Vehicle("BrandA", "CarA");
        Vehicle carB = new Vehicle("BrandB", "CarB");

        carA.speedUp(30);
        carB.speedUp(40);
    }
}

class Vehicle{
    private String brandName;
    private String vehicleName;

    public Vehicle(String brandName, String vehicleName){
        this.brandName = brandName;
        this.vehicleName =vehicleName;
    }

    public void speedUp(int increaseSpeed){
        System.out.println("This vehicle " + vehicleName + " with brand: "+ brandName + " speed up to "+ increaseSpeed);
    }
}

class Car extends Vehicle {
    public Car(String brandName, String vehicleName){
        
    }
}



