import sun.rmi.runtime.NewThreadAction;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Vehicle carA = new Vehicle("BrandA", "CarA");
        Vehicle carB = new Vehicle("BrandB", "CarB");

        carA.speedUp(30);
        carB.speedUp(40);

        Car car = new Car("GoodBye", "My Car");
        car.speedUp(180);
        car.speedUp(201);

        Driver driver = new Driver("Sam", carA);
        driver.speedUp(20);
    }
}

class Driver{
    private String name;
    private Vehicle vehicle;

    public Driver(String name, Vehicle vehicle){
        this.name = name;
        this.vehicle =vehicle;
    }

    public void speedUp(int increaseSpeed){
        System.out.println("Driver name: "+ this.name);
        this.vehicle.speedUp(increaseSpeed);
    }
}

class Vehicle {
    private String brandName;
    private String vehicleName;

    public Vehicle(String brandName, String vehicleName) {
        this.brandName = brandName;
        this.vehicleName = vehicleName;
    }

    public void speedUp(int increaseSpeed) {
        System.out.println("This vehicle " + vehicleName + " with brand: " + brandName + " speed up to " + increaseSpeed);
    }
}

class Car extends Vehicle {
    public Car(String brandName, String vehicleName) {
        super(brandName, vehicleName);
    }

    @Override
    public void speedUp(int increaseSpeed) {
        if (increaseSpeed < 200) {
            super.speedUp(increaseSpeed);
        } else {
            System.out.println("SpeedUp failed");
        }
    }
}



