import sun.rmi.runtime.NewThreadAction;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Vehicle carA = new Vehicle("BrandA", "CarA");
        Vehicle carB = new Vehicle("BrandB", "CarB");

        carA.speedUp(30);
        carB.speedUp(40);

        Vehicle car = new Car("GoodBye", "My Car");
        car.speedUp(180);
        car.speedUp(201);

        Vehicle bus = new Bus("BusBrand", "BusA");
        bus.speedUp(50);
        bus.speedUp(100);

        Driver driver = new Driver("Sam", carA);
        driver.speedUp(20);

        Driver jacky = new Driver("Jacky", car);
        jacky.speedUp(111);

        Driver bady = new Driver("Baby", bus);
        bady.speedUp(666);
    }
}

class Driver{
    private String name;
    private Vehicle vehicle;

    public Driver(String name, Vehicle vehicle){
        this.name = name;
        this.vehicle =vehicle;
    }

    public void speedUp(int increaseSpeed){
        System.out.println("Driver name: "+ this.name);
        this.vehicle.speedUp(increaseSpeed);
    }
}

class Vehicle {
    private String brandName;
    private String vehicleName;

    public Vehicle(String brandName, String vehicleName) {
        this.brandName = brandName;
        this.vehicleName = vehicleName;
    }

    public void speedUp(int increaseSpeed) {
        System.out.println("This vehicle " + vehicleName + " with brand: " + brandName + " speed up to " + increaseSpeed);
    }
}

class Car extends Vehicle {
    public Car(String brandName, String vehicleName) {
        super(brandName, vehicleName);
    }

    @Override
    public void speedUp(int increaseSpeed) {
        if (increaseSpeed < 200) {
            super.speedUp(increaseSpeed);
            System.out.println("__I am a Car__");
        } else {
            System.out.println("SpeedUp failed");
        }
    }
}

class Bus extends Vehicle {
    public Bus(String brandName, String vehicleName) {
        super(brandName, vehicleName);
    }

    @Override
    public void speedUp(int increaseSpeed) {
        if (increaseSpeed < 80) {
            super.speedUp(increaseSpeed);
            System.out.println("__I am a Bus__");
        } else {
            System.out.println("SpeedUp failed");
        }
    }
}



